# Methods parameters
qr:
  method: "gram_schmidt"
  tolerance: 1e-10

linear_systems:
  qr_solution:
    enabled: true
  seidel:
    enabled: true
    max_iterations: 100
    tolerance: 1e-3

nonlinear_equations:
  bisection:
    max_iterations: 100
    tolerance: 1e-3
  combined_method:
    max_iterations: 100
    tolerance: 1e-5

nonlinear_systems:
  newton:
    max_iterations: 100
    tolerance: 1e-4